package com.turbomc.storage;

import com.turbomc.config.TurboConfig;

import java.nio.file.Path;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.nio.file.Paths;

/**
 * Bootstrap initializer for TurboMC LRF storage system.
 * 
 * This class should be called early in the server startup process
 * to set up and migrate world regions according to turbo.toml configuration.
 */
public final class TurboLRFBootstrap {

    private TurboLRFBootstrap() {
    }

    private static void ensurePaperGlobalConfig(Path serverDirectory) {
        try {
            Path configDir = serverDirectory.resolve("config");
            Files.createDirectories(configDir);
            Path globalYml = configDir.resolve("paper-global.yml");
            String turboBlock = "turbo:\n" +
                    "  compression:\n" +
                    "    algorithm: lz4\n" +
                    "    auto-migrate: true\n" +
                    "    fallback-enabled: true\n" +
                    "    level: 6\n" +
                    "  proxy:\n" +
                    "    enabled: false\n" +
                    "    host: 127.0.0.1\n" +
                    "    port: 25577\n" +
                    "  storage:\n" +
                    "    auto-convert: true\n" +
                    "    conversion-mode: on-demand\n" +
                    "    format: lrf\n" +
                    "  version-control:\n" +
                    "    maximum-version: 1.21.10\n" +
                    "    minimum-version: 1.20.1\n";

            if (!Files.exists(globalYml)) {
                // Create new file with only turbo block
                Files.writeString(globalYml, "# Auto-generated by TurboMC\n" + turboBlock + "\n");
                System.out.println("[TurboMC][CFG] Created paper-global.yml with TurboMC section.");
                return;
            }
            // File exists; check if already has turbo section
            String content = Files.readString(globalYml);
            if (!content.contains("\nturbo:")) {
                // append at end
                Files.writeString(globalYml, "\n\n# TurboMC Settings\n" + turboBlock + "\n", java.nio.file.StandardOpenOption.APPEND);
                System.out.println("[TurboMC][CFG] Appended TurboMC section to paper-global.yml.");
            }
        } catch (Exception ex) {
            System.err.println("[TurboMC][CFG] Failed to ensure paper-global.yml: " + ex.getMessage());
        }
    }

    /**
     * Initialize TurboMC LRF system and run migrations if configured.
     * Should be called from MinecraftServer bootstrap or plugin initialization.
     * 
     * @param serverDirectory the server root directory (where turbo.toml is located)
     */
    public static void initialize(Path serverDirectory) {
        System.out.println("[TurboMC][LRF] Initializing LRF storage system...");

            // Ensure paper-global.yml contains TurboMC config section
            ensurePaperGlobalConfig(serverDirectory);

        try {
            // Load TurboMC configuration
            System.out.println("[TurboMC][LRF] Loading configuration...");
            TurboConfig config = TurboConfig.getInstance(serverDirectory.toFile());

            // Log storage configuration
            String storageFormat = config.getStorageFormat();
            boolean autoConvert = config.isAutoConvertEnabled();
            String conversionMode = config.getConversionMode();

            System.out.println("[TurboMC][LRF] Storage Format: " + storageFormat);
            System.out.println("[TurboMC][LRF] Auto-Convert: " + autoConvert);
            System.out.println("[TurboMC][LRF] Conversion Mode: " + conversionMode);

            // If auto-convert is enabled, migrate worlds
            if (autoConvert) {
                System.out.println("[TurboMC][LRF] Auto-convert enabled. Worlds will be migrated on load.");
            }

            System.out.println("[TurboMC][LRF] LRF storage system initialized successfully.");
        } catch (Exception e) {
            System.err.println("[TurboMC][LRF] Failed to initialize LRF storage system: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Initialize with default server directory (current working directory).
     */
    public static void initialize() {
        initialize(Paths.get("."));
    }

    /**
     * Migrate a specific world's regions if auto-convert is enabled.
     * Should be called when a world is about to be loaded.
     * 
     * @param worldDirectory the world directory (contains region/ folder)
     */
    public static void migrateWorldIfNeeded(Path worldDirectory) {
        try {
            TurboConfig config = TurboConfig.getInstance();
            config.migrateWorldRegionsIfNeeded(worldDirectory);
        } catch (Exception e) {
            System.err.println("[TurboMC][LRF] Failed to migrate world: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
