package com.turbomc.storage;

import com.mojang.brigadier.CommandDispatcher;
import com.turbomc.config.TurboConfig;
import com.turbomc.compression.TurboCompressionService;
import com.turbomc.storage.ConversionMode;
import com.turbomc.commands.TurboCommandRegistry;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.server.MinecraftServer;

import java.nio.file.Path;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.nio.file.Paths;

/**
 * Bootstrap initializer for TurboMC LRF storage system.
 * 
 * This class should be called early in the server startup process
 * to set up and migrate world regions according to turbo.toml configuration.
 */
public final class TurboLRFBootstrap {

    private TurboLRFBootstrap() {
    }

    private static void ensurePaperGlobalConfig(Path serverDirectory) {
        try {
            Path configDir = serverDirectory.resolve("config");
            Files.createDirectories(configDir);
            Path globalYml = configDir.resolve("paper-global.yml");
            String turboBlock = "turbo:\n" +
                    "  compression:\n" +
                    "    algorithm: lz4\n" +
                    "    auto-migrate: true\n" +
                    "    fallback-enabled: true\n" +
                    "    level: 6\n" +
                    "  proxy:\n" +
                    "    enabled: false\n" +
                    "    host: 127.0.0.1\n" +
                    "    port: 25577\n" +
                    "  storage:\n" +
                    "    auto-convert: true\n" +
                    "    conversion-mode: on-demand\n" +
                    "    format: lrf\n" +
                    "  version-control:\n" +
                    "    maximum-version: 1.21.10\n" +
                    "    minimum-version: 1.20.1\n";

            if (!Files.exists(globalYml)) {
                // Create new file with only turbo block
                Files.writeString(globalYml, "# Auto-generated by TurboMC\n" + turboBlock + "\n");
                System.out.println("[TurboMC][CFG] Created paper-global.yml with TurboMC section.");
                return;
            }
            // File exists; check if already has turbo section
            String content = Files.readString(globalYml);
            if (!content.contains("\nturbo:")) {
                // append at end
                Files.writeString(globalYml, "\n\n# TurboMC Settings\n" + turboBlock + "\n", java.nio.file.StandardOpenOption.APPEND);
                System.out.println("[TurboMC][CFG] Appended TurboMC section to paper-global.yml.");
            }
        } catch (Exception ex) {
            System.err.println("[TurboMC][CFG] Failed to ensure paper-global.yml: " + ex.getMessage());
        }
    }

    /**
     * Initialize TurboMC LRF system and run migrations if configured.
     * Should be called from MinecraftServer bootstrap or plugin initialization.
     * 
     * @param serverDirectory the server root directory (where turbo.toml is located)
     */
    public static void initialize(Path serverDirectory) {
        System.out.println("[TurboMC][LRF] Initializing LRF storage system...");

            // Ensure paper-global.yml contains TurboMC config section
            ensurePaperGlobalConfig(serverDirectory);

        try {
            // Load TurboMC configuration
            System.out.println("[TurboMC][LRF] Loading configuration...");
            TurboConfig config = TurboConfig.getInstance(serverDirectory.toFile());

            // Initialize compression service
            System.out.println("[TurboMC][LRF] Initializing compression service...");
            TurboCompressionService.initialize(config);

            // Log storage configuration
            String storageFormat = config.getStorageFormat();
            boolean autoConvert = config.isAutoConvertEnabled();
            ConversionMode conversionMode = config.getConversionModeEnum();

            System.out.println("[TurboMC][LRF] Storage Format: " + storageFormat);
            System.out.println("[TurboMC][LRF] Auto-Convert: " + autoConvert);
            System.out.println("[TurboMC][LRF] Conversion Mode: " + conversionMode.getConfigValue());

            // If auto-convert is enabled, show mode-specific message
            if (autoConvert) {
                switch (conversionMode) {
                    case FULL_LRF:
                        System.out.println("[TurboMC][LRF] Full LRF conversion enabled. All MCA files will be converted at startup.");
                        break;
                    case ON_DEMAND:
                        System.out.println("[TurboMC][LRF] On-demand conversion enabled. MCA files will be converted as chunks are loaded.");
                        break;
                    case BACKGROUND:
                        System.out.println("[TurboMC][LRF] Background conversion enabled. MCA files will be converted during idle server time.");
                        break;
                    case MANUAL:
                        System.out.println("[TurboMC][LRF] Manual conversion mode. Use conversion API to convert MCA files.");
                        break;
                }
            }

            System.out.println("[TurboMC][LRF] LRF storage system initialized successfully.");
            
            // Initialize the Turbo Storage Manager with all advanced features
            System.out.println("[TurboMC][LRF] Initializing Turbo Storage Manager...");
            TurboStorageManager storageManager = TurboStorageManager.getInstance();
            storageManager.initialize();
            
            // Install storage hooks for seamless integration with Paper's chunk system
            System.out.println("[TurboMC][LRF] Installing storage hooks...");
            TurboStorageHooks.installHooks();
            
            // Register TurboMC commands
            System.out.println("[TurboMC][LRF] Registering TurboMC commands...");
            // Note: Commands will be registered later in SpigotConfig.registerCommands()
            
            // If FULL_LRF mode is enabled, perform migration now
            if (conversionMode == ConversionMode.FULL_LRF && autoConvert) {
                performFullLRFMigration(serverDirectory);
            }
        } catch (Exception e) {
            System.err.println("[TurboMC][LRF] Failed to initialize LRF storage system: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Initialize with default server directory (current working directory).
     */
    public static void initialize() {
        initialize(Paths.get("."));
    }

    /**
     * Migrate a specific world's regions if auto-convert is enabled.
     * Should be called when a world is about to be loaded.
     * 
     * @param worldDirectory the world directory (contains region/ folder)
     */
    public static void migrateWorldIfNeeded(Path worldDirectory) {
        try {
            // Check if TurboConfig is initialized
            if (!TurboConfig.isInitialized()) {
                System.out.println("[TurboMC][LRF] TurboConfig not yet initialized, skipping world migration for: " + worldDirectory);
                return;
            }
            
            TurboConfig config = TurboConfig.getInstance();
            ConversionMode conversionMode = config.getConversionModeEnum();
            
            // Only migrate if automatic conversion is enabled
            if (conversionMode.isAutomaticConversion()) {
                config.migrateWorldRegionsIfNeeded(worldDirectory);
            }
        } catch (Exception e) {
            System.err.println("[TurboMC][LRF] Failed to migrate world: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Perform full LRF migration for all worlds during startup.
     * Should be called during server initialization when FULL_LRF mode is enabled.
     * 
     * @param serverDirectory the server root directory
     */
    public static void performFullLRFMigration(Path serverDirectory) {
        try {
            TurboConfig config = TurboConfig.getInstance(serverDirectory.toFile());
            ConversionMode conversionMode = config.getConversionModeEnum();
            
            if (conversionMode != ConversionMode.FULL_LRF) {
                return; // Only run in FULL_LRF mode
            }
            
            if (!config.isAutoConvertEnabled()) {
                return; // Auto-convert must be enabled
            }
            
            System.out.println("[TurboMC][LRF] Starting full LRF migration for all worlds...");
            
            // Common world directories
            String[] worldNames = {"world", "world_nether", "world_the_end"};
            
            for (String worldName : worldNames) {
                Path worldDir = serverDirectory.resolve(worldName);
                if (Files.isDirectory(worldDir)) {
                    System.out.println("[TurboMC][LRF] Migrating world: " + worldName);
                    // Use the full LRF conversion mode
                    config.migrateWorldRegionsIfNeeded(worldDir);
                }
            }
            
            System.out.println("[TurboMC][LRF] Full LRF migration completed for all worlds.");
            
        } catch (Exception e) {
            System.err.println("[TurboMC][LRF] Failed to perform full LRF migration: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
